use_frameworks!

target 'GeneralTableView_Example' do
  pod 'GeneralTableView', :path => '../'

  target 'GeneralTableView_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
